# Generated by Django 3.2.9 on 2021-12-27 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(auto_created=True, max_length=1000, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Product name')),
                ('TypeOfProduct', models.CharField(max_length=150, unique=True, verbose_name='Type of furniture')),
                ('ModelOfProduct', models.CharField(max_length=150, unique=True, verbose_name='Furniture model')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('ID', models.AutoField(auto_created=True, max_length=1000, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('productname', models.CharField(max_length=150, unique=True, verbose_name='Product name')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.AutoField(auto_created=True, max_length=1000, primary_key=True, serialize=False, verbose_name='User ID')),
                ('UserName', models.CharField(max_length=150, unique=True, verbose_name='NickName')),
                ('password', models.CharField(max_length=30, unique=True, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
